### PR TITLE
add option to enable clock_gettime

### PR DESCRIPTION
**Pull request by davidzengxhsh**
This PR is trying to enhance the enable/disable clock_gettime.  
Add a new command option(-c) to enable clock_gettime at boot time.

### CODE REVIEW

**Comment by davidzengxhsh** [comment]
I found there is still a problem with the (-c) option. 
With this sequence: 
_with "-c" in the command; 
enable 0 range; 
start 0;_
Then I can get only 93Mpps.

But with this sequence:
_without "-c" in the command line;
enable clock_gettime;
enable 0 range;
start 0_
or this sequence:
_with "-c" in the command line;
start 0_
I can get 144.8Mpps.

**Comment by KeithWiles** [comment]
In range mode are you changing the packet size, if so that could be the reason the rate is lower.

**Comment by davidzengxhsh** [comment]
> In range mode are you changing the packet size, if so that could be the reason the rate is lower.

I am not changing the pkt size. It seems using clock_gettime needs more cores to achieve the line rate.

**Comment by davidzengxhsh** [comment]
Here is the command and screenshot: 
./Builddir/app/pktgen --file-prefix pktgen -a 0000:01:00.0 -a 0000:01:00.1 -l 40-79 -n 8 -- -N -T -m [42-43:44-69].0 -c
image

**Review by pktgen — APPROVED** [review]
Thanks

**Pull request merged**
